In [113]:
# get scores from sagemaker aws private workforces

from boto3 import client
import boto3
import json
import pandas as pd

s3 = boto3.resource('s3')
col_names =  ['image', 'label']
my_df  = pd.DataFrame(columns = col_names)

conn = client('s3')  # again assumes boto.cfg setup, assume AWS S3

for key in conn.list_objects(Bucket='workattr',Prefix='iteration-1')['Contents']:
    
    content_object = s3.Object('workattr', key['Key'])
    
    body=content_object.get()['Body'].read()
    
    my_json = body.decode('utf8').replace("'", '"')
    
    data = json.loads(my_json)
    
    for x in data:
        
        my_df.loc[len(my_df)] = [x['dataObject']['s3Uri'],x['annotations'][0]['annotationData']['content'][36]]

my_df.sort_values("image", inplace = True) 
    
my_df.to_excel("latino_male_21.xlsx")

In [28]:
# get scores from sagemaker aws public workforces - AMT

from boto3 import client
import boto3
import json
import pandas as pd

s3 = boto3.resource('s3')
col_names =  ['image','rater','label']
my_df  = pd.DataFrame(columns = col_names)

conn = client('s3')  # again assumes boto.cfg setup, assume AWS S3

for key in conn.list_objects(Bucket='workattr',Prefix='iteration-2')['Contents']:
    
    content_object = s3.Object('workattr', key['Key'])
    
    body=content_object.get()['Body'].read()
    
    my_json = body.decode('utf8').replace("'", '"')
    
    data = json.loads(my_json)
    
    for x in data:
         
        for y in x['annotations']:
            my_df.loc[len(my_df)] = [x['dataObject']['s3Uri'],y['workerId'],y['annotationData']['content']]

my_df.sort_values("image", inplace = True) 

#my_df['image'] = my_df['image'].str.replace(r'\D', '') 
my_df['label']= my_df['label'].str.replace(r'{"crowd-image-classifier":{"label":"', '') 
my_df['image']= my_df['image'].str.replace(r's3://ecust-fbp-male/', '')  
my_df['rater']= my_df['rater'].str.replace(r'public.us-east-1.', '')  
my_df['label']= my_df['label'].str.replace(r'"}}', '') 
my_df.to_excel("pub_date_all5_2.xlsx")
#my_df

In [143]:
#create score matrix - private scores
import os
import pandas as pd
DIR ='/home/ec2-user/SageMaker/private_generic')
files = os.listdir(DIR)
files_xls = [f for f in files if f[-4:] == 'xlsx']

df=pd.DataFrame(columns = ['image','label'])
prefix_x=''

for f in files_xls:
    prefix_y=f
    data = pd.read_excel(f, 'Sheet1',usecols = "B:C")    
    df=pd.merge(df,data,on = "image", how='outer', suffixes=(prefix_x, prefix_y))
    prefix_x=f
    
#df['mean'] = df.mean(axis=1)    
df.to_excel("private_generic.xlsx")

'\ndf = pd.read_excel("gen_guys1.xlsx")\ndf2 = pd.read_excel("gen_guys2.xlsx")\ndf3 = pd.read_excel("gen_guys3.xlsx")\ndf4 = pd.read_excel("gen_guys4.xlsx")\nmatrix = df.pivot_table(columns=\'rater\', index=\'image\', values=\'label\').reset_index()\nmatrix2 = df2.pivot_table(columns=\'rater\', index=\'image\', values=\'label\').reset_index()\nmatrix3 = df3.pivot_table(columns=\'rater\', index=\'image\', values=\'label\').reset_index()\nmatrix4 = df4.pivot_table(columns=\'rater\', index=\'image\', values=\'label\').reset_index()\n#matrix.columns.intersection(matrix2.columns)\nresult = pd.merge(matrix, matrix2, on="image")\nresult = pd.merge(result, matrix3, on="image")\nresult = pd.merge(result, matrix4, on="image")\n\n\nresult[\'mean\'] = result.mean(axis=1)\n\nresult.to_excel("guys_mean.xlsx")\n'

In [165]:
#common image names
female = pd.read_excel('private_date_female.xlsx') 
male = pd.read_excel('private_date_male.xlsx')
s1 = pd.merge(female, male, how='inner', on=['image'])
s1

,Unnamed: 0_x,image,labelcaucasian_female_29.xlsx,labelcaucasian_female_27.xlsx,labelcaucasian_female_31.xlsx,labelasian_female_22.xlsx,labelcaucasian_female_32.xlsx,labelblack_female_22.xlsx,labelasian_female_25.xlsx,labelcaucasian_female_34.xlsx,...,labelcaucasian_male_39.xlsx,labelcaucasian_male_49.xlsx,labelmideast_male_20.xlsx,labelasian_male_27.xlsx,labelhispanic_male_29.xlsx,labelasian_male_20.xlsx,labelcaucasian_male_37.xlsx,labelblack_male_37.xlsx,caucasian_male_39,mean_y
0,3,11,5.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,1.0,NaN,2.0,5.0,2.750000
1,13,12,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,3.0,NaN,NaN,NaN,4.0,NaN,7.0,NaN,4.666667
2,24,13,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,9.0,3.0,4.333333
3,32,14,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN,1.500000
4,37,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,2.0,1.0,1.333333
5,38,3,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.000000
6,39,4,7.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,5.0,NaN,NaN,4.0,NaN,2.0,4.0,3.750000
7,40,5,1.0,NaN,2.0,NaN,NaN,NaN,1.0,NaN,...,NaN,7.0,NaN,NaN,NaN,3.0,NaN,2.0,NaN,4.000000
8,41,6,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,6.000000
9,43,8,1.0,NaN,3.0,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,8.0,NaN,5.500000
10,79,ankush-minda-uPIDtOdCINY-unsplash,1.0,NaN,2.0,1.0,4.0,1.0,1.0,4.0,...,5.0,NaN,NaN,1.0,NaN,NaN,1.0,1.0,NaN,2.000000
11,88,ashkan-forouzani-Y8QiDJMEUGc-unsplash,2.0,NaN,NaN,NaN,7.0,8.0,NaN,2.0,...,6.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,2.250000
12,90,ashkan-forouzani-YzsFkMBMhoQ-unsplash,1.0,1.0,1.0,NaN,1.0,1.0,NaN,1.0,...,2.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,1.250000
13,255,girl1,7.0,NaN,1.0,NaN,8.0,1.0,NaN,1.0,...,8.0,NaN,NaN,5.0,9.0,7.0,1.0,2.0,NaN,5.333333
14,256,girl2,7.0,NaN,1.0,1.0,5.0,1.0,NaN,1.0,...,9.0,NaN,NaN,3.0,NaN,NaN,9.0,3.0,NaN,6.000000
15,708,3,NaN,5.0,NaN,NaN,1.0,1.0,NaN,2.0,...,5.0,NaN,NaN,NaN,8.0,NaN,2.0,NaN,NaN,5.000000
16,709,4,NaN,7.0,NaN,3.0,4.0,1.0,NaN,8.0,...,4.0,NaN,NaN,NaN,7.0,NaN,1.0,NaN,NaN,4.000000
17,710,5,NaN,2.0,NaN,NaN,6.0,5.0,NaN,3.0,...,7.0,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,6.000000
18,711,1,NaN,NaN,NaN,4.0,6.0,8.0,NaN,5.0,...,9.0,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,6.500000
19,714,2,NaN,NaN,NaN,1.0,3.0,1.0,NaN,1.0,...,5.0,NaN,NaN,1.0,4.0,NaN,4.0,NaN,NaN,3.500000
20,717,11,NaN,NaN,NaN,NaN,5.0,1.0,NaN,6.0,...,5.0,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,6.000000
21,723,12,NaN,NaN,NaN,NaN,7.0,1.0,NaN,6.0,...,6.0,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,7.500000
22,728,13,NaN,NaN,NaN,NaN,4.0,1.0,NaN,2.0,...,5.0,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,3.500000
23,734,14,NaN,NaN,NaN,NaN,7.0,1.0,NaN,6.0,...,7.0,NaN,NaN,NaN,7.0,NaN,5.0,NaN,NaN,6.333333
24,738,6,NaN,NaN,NaN,NaN,7.0,1.0,NaN,5.0,...,4.0,NaN,NaN,NaN,7.0,NaN,3.0,NaN,NaN,4.666667
25,739,7,NaN,NaN,NaN,NaN,7.0,1.0,NaN,3.0,...,4.0,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,3.500000
26,740,8,NaN,NaN,NaN,NaN,7.0,4.0,NaN,6.0,...,4.0,NaN,NaN,1.0,NaN,NaN,2.0,NaN,NaN,2.333333
27,741,9,NaN,NaN,NaN,NaN,7.0,8.0,NaN,6.0,...,5.0,NaN,NaN,4.0,8.0,NaN,4.0,NaN,NaN,5.250000

In [15]:
import zipfile
#os.chdir('/home/ec2-user/SageMaker')
with zipfile.ZipFile("5.zip","r") as zip_ref:
    zip_ref.extractall("123")

In [17]:
import os
list = os.listdir("4_crop") # dir is your directory path
number_files = len(list)
number_files

297

In [18]:
#images cropping
from PIL import Image
from autocrop import Cropper
import os
cropper = Cropper()
files=os.listdir('4-5')
for file in files:
    print(file)
    img_path = os.path.join('4-5', file)
    
    try:    
        cropped_array = cropper.crop(img_path)
        cropped_image = Image.fromarray(cropped_array)
        width, height = cropped_image.size
        print(width, height)
        cropped_image.save('./4_crop/'+file)
    except:
        print('no face',file)

pexels-hải-nguyễn-3616937.jpg
500 500
pexels-neeraj-raj-2767612.jpg
no face pexels-neeraj-raj-2767612.jpg
pexels-nh-noyon-4250841.jpg
no face pexels-nh-noyon-4250841.jpg
pexels-nichole-sebastian-3220360.jpg
no face pexels-nichole-sebastian-3220360.jpg
pexels-moose-photos-1036643.jpg
500 500
pexels-fauzan-ahmad-muzakky-2698444.jpg
500 500
pexels-dalila-dalprat-1853049.jpg
500 500
pexels-gabby-k-5384445.jpg
500 500
pexels-jermaine-ulinwa-3289153.jpg
500 500
pexels-cottonbro-4904569.jpg
no face pexels-cottonbro-4904569.jpg
pexels-christina-morillo-1181519.jpg
no face pexels-christina-morillo-1181519.jpg
pexels-marcelo-chagas-1893075.jpg
no face pexels-marcelo-chagas-1893075.jpg
pexels-manjeet-singh-yadav-1162983.jpg
500 500
pexels-shahi-zidan-2692577.jpg
500 500
pexels-athena-1831792.jpg
500 500
pexels-teddy-joseph-2955376.jpg
500 500
pexels-meijii-1638400.jpg
no face pexels-meijii-1638400.jpg
model-woman-1082219_1920.jpg
no face model-woman-1082219_1920.jpg
pexels-maria-orlova-4940726.jpg
no face pexels-maria-orlova-4940726.jpg
pexels-marlon-schmeiski-6115354.jpg
500 500
woman-984247_1920.jpg
500 500
pexels-jeremyhann-2898040.jpg
no face pexels-jeremyhann-2898040.jpg
pexels-abhishek-goel-1362724.jpg
no face pexels-abhishek-goel-1362724.jpg
pexels-daniel-xavier-1239288 (1).jpg
500 500
pexels-kalpit-4255591.jpg
500 500
pexels-duy-dinh-3614523.jpg
500 500
beautiful-1869534_1920.jpg
500 500
pexels-ryutaro-tsukata-6249088.jpg
500 500
pexels-rahul-pandit-5382522.jpg
500 500
pexels-riya-kumari-1739502.jpg
no face pexels-riya-kumari-1739502.jpg
pexels-mikhail-nilov-6620663.jpg
500 500
pexels-areous-ahmad-2122949.jpg
500 500
girl-517524_1920.jpg
500 500
pexels-javon-swaby-2778211.jpg
500 500
pexels-happy-pixels-3170437.jpg
500 500
pexels-kenex-media-sa-6573686.jpg
500 500
pexels-º╘º╤º▀º∩ºΓº╒º∩º▀º∩-º╥ºσº▌º╘º╤º▀ºΣº╤º▐º┌ºΓ-3847716.jpg
no face pexels-º╘º╤º▀º∩ºΓº╒º∩º▀º∩-º╥ºσº▌º╘º╤º▀ºΣº╤º▐º┌ºΓ-3847716.jpg
pexels-nappy-935969.jpg
500 500
pexels-the-baljinder-4089881.jpg
500 500
pexels-min-an-1070751.jpg
500 500
pexels-leonne-brito-1844012.jpg
500 500
pexels-anil-3794240.jpg
no face pexels-anil-3794240.jpg
pexels-timothy-works-3815254.jpg
no face pexels-timothy-works-3815254.jpg
pexels-samad-ismayilov-735552.jpg
500 500
man-5937492_1920.jpg
500 500
pexels-cottonbro-4100430.jpg
500 500
pexels-thunyarat-klaiklang-1814538.jpg
500 500
pexels-artem-podrez-5125221.jpg
500 500
pexels-engin-akyurt-3168993.jpg
500 500
pexels-askar-abayev-5638731.jpg
500 500
pexels-bestbe-models-2282520.jpg
500 500
pexels-ash-valiente-3533228.jpg
no face pexels-ash-valiente-3533228.jpg
pexels-olya-kobruseva-4550985.jpg
no face pexels-olya-kobruseva-4550985.jpg
pexels-maksim-goncharenok-5506095.jpg
500 500
girl-4549327_1920.jpg
no face girl-4549327_1920.jpg
pexels-zorro-zombie-1261998.jpg
500 500
women-5930352_1920.jpg
500 500
pexels-gabriela-pereira-1844140.jpg
no face pexels-gabriela-pereira-1844140.jpg
pexels-fotografierende-1793059.jpg
500 500
pexels-dalila-dalprat-1995129.jpg
500 500
pexels-rafi-ahmed-haven-1253364.jpg
500 500
man-5465729_1920.jpg
500 500
pexels-jan-valle-4061161.jpg
500 500
pexels-rodnae-productions-4911184.jpg
500 500
pexels-gabby-k-5303015.jpg
500 500
pexels-icapture-studios-3561145.jpg
500 500
pexels-teddy-joseph-2955375.jpg
500 500
pexels-mabel-lee-2739792.jpg
500 500
pexels-nichole-sebastian-3323208.jpg
no face pexels-nichole-sebastian-3323208.jpg
pexels-cristian-benavides-3662357.jpg
no face pexels-cristian-benavides-3662357.jpg
pexels-jt-kim-914472.jpg
no face pexels-jt-kim-914472.jpg
pexels-caleb-oquendo-3038287.jpg
no face pexels-caleb-oquendo-3038287.jpg
pexels-pravin-maniam-2728649.jpg
500 500
pexels-anna-shvets-3746226.jpg
no face pexels-anna-shvets-3746226.jpg
pexels-jahidul-islam-mohon-3725497.jpg
no face pexels-jahidul-islam-mohon-3725497.jpg
pexels-jonnas-duarte-3116018.jpg
no face pexels-jonnas-duarte-3116018.jpg
smile-1485850_1920.jpg
no face smile-1485850_1920.jpg
pexels-rodnae-productions-5837217.jpg
no face pexels-rodnae-productions-5837217.jpg
face-5084530_1920.jpg
no face face-5084530_1920.jpg
pexels-min-an-732425.jpg
500 500
man-5923039_1920.jpg
500 500
pexels-du-photographer-1843667.jpg
500 500
pexels-yogendra-singh-3748221.jpg
500 500
pexels-cottonbro-3419693.jpg
500 500
pexels-macharia-edson-2914149.jpg
500 500
pexels-harsh-raj-gond-2245035.jpg
500 500
pexels-bran-sodre-1852345.jpg
500 500
pexels-min-an-1165647.jpg
no face pexels-min-an-1165647.jpg
pexels-pixabay-247322.jpg
500 500
pexels-ketut-subiyanto-4584488.jpg
no face pexels-ketut-subiyanto-4584488.jpg
woman-2773007_1920.jpg
500 500
pexels-ron¿║-ferreira-2304113.jpg
500 500
pexels-the-lazy-artist-gallery-1149840.jpg
500 500
woman-5775938_1920.jpg
500 500
portrait-5938717_1920.jpg
no face portrait-5938717_1920.jpg
pexels-mentatdgt-2558680.jpg
500 500
pexels-ricael-sousa-1837158.jpg
500 500
pexels-cottonbro-6214874.jpg
500 500
pexels-italo-melo-2379005.jpg
500 500
pexels-cottonbro-4255413.jpg
500 500
pexels-harsh-raj-gond-2244975.jpg
no face pexels-harsh-raj-gond-2244975.jpg
woman-5939698_1920.jpg
500 500
pexels-mwabonje-2096476.jpg
500 500
pexels-steven-arenas-620074.jpg
500 500
pexels-jorge-fakhouri-filho-1852015.jpg
500 500
pexels-toni-ph-2040376.jpg
500 500
pexels-min-an-1589369.jpg
500 500
thanks-1209247_1920.jpg
500 500
pexels-min-an-1157461.jpg
500 500
pexels-noa-photography-4364604.jpg
500 500
pexels-ketut-subiyanto-4307713.jpg
500 500
hello-5919349_1920.jpg
500 500
pexels-murat-esibatir-4355346.jpg
500 500
pexels-dellon-thomas-3674248.jpg
500 500
pexels-ingrid-santana-2253707.jpg
500 500
pexels-nh-noyon-4250862.jpg
500 500
pexels-deden-dicky-ramdhani-2916324.jpg
no face pexels-deden-dicky-ramdhani-2916324.jpg
pexels-devil-imran-6414067.jpg
500 500
pexels-anna-tarazevich-5119607.jpg
500 500
pexels-rodnae-productions-4910538.jpg
no face pexels-rodnae-productions-4910538.jpg
pexels-mentatdgt-1167134.jpg
500 500
pexels-meijii-2014864.jpg
500 500
pexels-min-an-898768.jpg
500 500
pexels-ike-louie-natividad-2709388.jpg
500 500
pexels-the-baljinder-1856477.jpg
no face pexels-the-baljinder-1856477.jpg
pexels-ravi-k-938639.jpg
no face pexels-ravi-k-938639.jpg
pexels-ingrid-santana-2100063.jpg
500 500
portrait-2865605_1920.jpg
500 500
pexels-anna-tarazevich-5119587.jpg
500 500
pexels-italo-melo-2379004.jpg
500 500
pexels-ricael-sousa-1837158 (1).jpg
500 500
pexels-prince-photos-1537517.jpg
500 500
pexels-rodrigo-souza-2531553.jpg
500 500
pexels-pratik-gupta-2858965.jpg
no face pexels-pratik-gupta-2858965.jpg
pexels-ike-louie-natividad-2462047.jpg
no face pexels-ike-louie-natividad-2462047.jpg
smile-4662474_1920.jpg
500 500
pexels-gaurav-ranjitkar-4095473.jpg
500 500
pexels-jc-romero-3236737.jpg
500 500
pexels-trung-nguyen-2435583 (1).jpg
500 500
pexels-hamid-tajik-6273203.jpg
500 500
man-5937491_1920.jpg
no face man-5937491_1920.jpg
pexels-the-baljinder-4089883.jpg
no face pexels-the-baljinder-4089883.jpg
girl-1018414_1920.jpg
500 500
pexels-cottonbro-4505450.jpg
500 500
portrait-1833929_1920.jpg
500 500
pexels-tuấn-kiệt-jr-1535051.jpg
no face pexels-tuấn-kiệt-jr-1535051.jpg
pexels-tuấn-kiệt-jr-1789921.jpg
no face pexels-tuấn-kiệt-jr-1789921.jpg
eyes-5938203_1920.jpg
500 500
pexels-tom-leishman-5255073.jpg
no face pexels-tom-leishman-5255073.jpg
pexels-creative-hussain-2774197.jpg
no face pexels-creative-hussain-2774197.jpg
girl-5934674_1920.jpg
500 500
people-2587179_1920.jpg
500 500
pexels-armin-rimoldi-5301742.jpg
500 500
pexels-ali-pazani-2787341.jpg
500 500
pexels-murat-esibatir-4355346 (1).jpg
500 500
pexels-pixabay-35551.jpg
500 500
pexels-ketut-subiyanto-4307688.jpg
500 500
pexels-mentatdgt-1306557.jpg
500 500
pexels-kebs-visuals-3676424.jpg
no face pexels-kebs-visuals-3676424.jpg
pexels-jermaine-ulinwa-3321515.jpg
500 500
pexels-cottonbro-5532846.jpg
500 500
pexels-joy-deb-1580270.jpg
no face pexels-joy-deb-1580270.jpg
pexels-ezekixl-akinnewu-950243.jpg
500 500
pexels-wesley-rocha-3797438.jpg
500 500
pexels-zack-jarosz-2024901.jpg
500 500
handsome-guy-5891610_1920.jpg
500 500
pexels-trung-nguyen-2435583.jpg
500 500
pexels-timothy-works-3918017.jpg
no face pexels-timothy-works-3918017.jpg
pexels-amal-hakim-busran-2746025.jpg
no face pexels-amal-hakim-busran-2746025.jpg
pexels-sora-shimazaki-5938437.jpg

500 500
man-5928801_1920.jpg
500 500
pexels-marcelo-chagas-2535859.jpg
500 500
pexels-min-an-1586654.jpg
500 500
pexels-mentatdgt-936225.jpg
no face pexels-mentatdgt-936225.jpg
girl-1888161_1920.jpg
500 500
pexels-bharat-kumar-2055033.jpg
500 500
man-1129953_1920.jpg
500 500
pexels-marlon-schmeiski-3839904.jpg
500 500
asian-653899_1920.jpg
no face asian-653899_1920.jpg
pexels-jameson-mallari-atenta-2872703.jpg
500 500
pexels-anna-tarazevich-5234265.jpg
500 500
pexels-jaysen-scott-1858490.jpg
500 500
pexels-skg-photography-2270078.jpg
500 500
pexels-azraq-al-rezoan-5641188.jpg
500 500
pexels-ali-pazani-2811087.jpg
500 500
pexels-pixabay-235534.jpg
no face pexels-pixabay-235534.jpg
pexels-mart¿¬-pardo-1674318.jpg
500 500
pexels-salah-amrani-1232459.jpg
no face pexels-salah-amrani-1232459.jpg
pexels-andrea-piacquadio-3768877.jpg
500 500
portrait-2194457_1920.jpg
no face portrait-2194457_1920.jpg
pexels-shivkumar-sd-1379031.jpg
no face pexels-shivkumar-sd-1379031.jpg
pexels-nesto-1676213.jpg
500 500
pexels-reafon-gates-2566927.jpg
no face pexels-reafon-gates-2566927.jpg
girl-5933162_1920.jpg
500 500
pexels-keli-santos-1853268.jpg
500 500
pexels-min-an-1153351.jpg
500 500
pexels-ketut-subiyanto-4307733.jpg
500 500
thinking-5931999_1920.jpg
no face thinking-5931999_1920.jpg
makeup-1442912_1920.jpg
500 500
pexels-bran-sodre-1856538.jpg
500 500
pexels-daniel-xavier-1239288.jpg
500 500
pexels-ketut-subiyanto-4584579.jpg
500 500
pexels-adrienne-andersen-2661256.jpg
500 500
pexels-emre-keshavarz-3518392.jpg
500 500
pexels-atul-choudhary-2753381.jpg
500 500
children-82272_1920.jpg
500 500
pexels-nicole-michalou-5778909.jpg
500 500
pexels-yogendra-singh-5499219.jpg
500 500
pexels-marcelo-chagas-2291012.jpg
500 500
pexels-tuấn-kiệt-jr-1391499.jpg
500 500
guard-1129949_1920.jpg
500 500
pexels-azraq-al-rezoan-5151189.jpg
500 500
pexels-rahul-shah-1208015.jpg
no face pexels-rahul-shah-1208015.jpg
pexels-juan-n-gomez-2589650.jpg
500 500
pexels-samson-katt-5256700.jpg
500 500
pexels-gatot-adri-2693621.jpg
500 500
pexels-marcelo-dias-2448994.jpg
500 500
pexels-sigit-hidayat-1767557.jpg
500 500
pexels-zain-ali-905470.jpg
500 500
man-5913899_1920.jpg
no face man-5913899_1920.jpg
pexels-ayaka-kato-2860892.jpg
500 500
young-girl-510441_1920.jpg
500 500
pexels-darshan-peeal-2784078.jpg
500 500
pexels-jay-rane-943235.jpg
no face pexels-jay-rane-943235.jpg
pexels-shubham-sharma-2912695.jpg
500 500
pexels-jameson-mallari-atenta-3008355.jpg
500 500
pexels-marcelo-chagas-2121531.jpg
500 500
pexels-ali-pazani-2811089.jpg
500 500
pexels-prayoon-sajeev-2897507.jpg
no face pexels-prayoon-sajeev-2897507.jpg
pexels-ginu-joseph-4437265.jpg
no face pexels-ginu-joseph-4437265.jpg
vishal-shiro-5935497_1920.jpg
500 500
boy-1119239_1920.jpg
500 500
model-4605248_1920.jpg
500 500
pexels-perchek-industrie-1702238.jpg
no face pexels-perchek-industrie-1702238.jpg
pexels-matheus-henrin-2071150.jpg
500 500
pexels-julia-m-cameron-4144453.jpg
no face pexels-julia-m-cameron-4144453.jpg
pexels-carol-wd-3454302.jpg
500 500
pexels-arvind-shakya-796557.jpg
500 500
pexels-marcelo-dias-2169500.jpg
no face pexels-marcelo-dias-2169500.jpg
kids-2408614_1920.jpg
500 500
pexels-chris-thornton-1252246.jpg
no face pexels-chris-thornton-1252246.jpg
pexels-nguyễn-lâm-886477.jpg
500 500
5
no face 5
woman-5932291_1920.jpg
500 500
pexels-anubhaw-anand-3263992.jpg
500 500
pexels-min-an-698551.jpg
no face pexels-min-an-698551.jpg
child-3199624_1920.jpg
500 500
pexels-cem-saka-3881545.jpg
no face pexels-cem-saka-3881545.jpg
pexels-dhemer-gonçalves-3036415.jpg
500 500
pexels-cottonbro-3419647.jpg
500 500
pexels-fauzan-ahmad-muzakky-2709745.jpg
no face pexels-fauzan-ahmad-muzakky-2709745.jpg
pexels-ba-phi-1752126.jpg
500 500
pexels-thor-garlan-3431567.jpg
no face pexels-thor-garlan-3431567.jpg
pexels-cottonbro-5319510.jpg
500 500
pexels-min-an-752802.jpg
500 500
pexels-willsantt-1962844.jpg
500 500
pexels-rodnae-productions-4911467.jpg
no face pexels-rodnae-productions-4911467.jpg
pexels-marx-ilagan-616376.jpg
no face pexels-marx-ilagan-616376.jpg
pexels-bess-hamiti-35537.jpg
500 500
pexels-mikhail-nilov-6612835.jpg
500 500
pexels-anna-shvets-4672292.jpg
no face pexels-anna-shvets-4672292.jpg
pexels-anna-shvets-4672555.jpg
500 500
computer-2937216_1920.jpg
no face computer-2937216_1920.jpg
pexels-min-an-991217.jpg
500 500
pexels-min-an-751204.jpg
500 500
pexels-hamid-tajik-6207046.jpg
500 500
pexels-raul-reynoso-1578531.jpg
500 500
pexels-mwabonje-2680369.jpg
500 500
pexels-rafael-freire-5714735.jpg
500 500
pexels-dellon-thomas-3189024.jpg
500 500
pexels-ketut-subiyanto-4473405.jpg
500 500
pexels-cottonbro-4505454.jpg
no face pexels-cottonbro-4505454.jpg
pexels-richi-choraria-2525582.jpg
no face pexels-richi-choraria-2525582.jpg
pexels-george-ikwegbu-2379429.jpg
500 500
pexels-arsham-haghani-3536991.jpg
500 500
pexels-ike-louie-natividad-3310695.jpg
500 500
girl-5934632_1920.jpg
500 500
man-5465741_1920.jpg
500 500
pexels-bernard-ng-3318310.jpg
500 500
pexels-luiz-fernando-3021593.jpg
500 500
pexels-rahul-shah-888956.jpg
500 500
pexels-cxpturing-souls-3054983.jpg
no face pexels-cxpturing-souls-3054983.jpg
pexels-tima-miroshnichenko-5988665.jpg
500 500
pexels-emre-keshavarz-5145180.jpg
no face pexels-emre-keshavarz-5145180.jpg
pexels-min-an-1645820.jpg
no face pexels-min-an-1645820.jpg
pexels-min-an-1165641.jpg
500 500
pretty-2111498_1920.jpg
500 500
pexels-anete-lusina-5721443.jpg
500 500
pexels-ketut-subiyanto-4350112.jpg
500 500
pexels-tomaz-barcellos-1987301.jpg
500 500
pexels-griffin-wooldridge-3970083.jpg
500 500
pexels-spencer-selover-775358.jpg
500 500
pexels-ibadat-singh-2955247.jpg
500 500
pexels-ibadat-singh-2586823.jpg
500 500
people-2564463_1920.jpg
no face people-2564463_1920.jpg
pexels-viktoria-slowikowska-5332337.jpg
no face pexels-viktoria-slowikowska-5332337.jpg
pexels-mahmoud-gamal-674685.jpg
no face pexels-mahmoud-gamal-674685.jpg

In [15]:
import shutil
shutil.make_archive('scores', 'zip', './scores/')

'/home/ec2-user/SageMaker/scores.zip'

In [14]:
#create score matrix - public AMT scores
import os
import pandas as pd
DIR = '/home/ec2-user/SageMaker/public_date/'
files = os.listdir(DIR)
files_xls = [f for f in files if f[-4:] == 'xlsx']
df=pd.DataFrame(columns = ['image','rater'])
prefix_x=''

for f in files_xls:
   # if '_male' in f:
       print(f) 
       data = pd.read_excel(DIR+f, 'Sheet1',usecols = "B:D") 
       data['image']= data['image'].str.replace(r's3://allattrimages/', '') 
       matrix = data.pivot_table(columns='rater', index='image', values='label').reset_index()
       df=pd.merge(df,matrix,on = "image", how='outer')

df1=df['image']
df = df.drop(['image', 'rater'], axis=1)
df3 = df.groupby(df.columns.str.split("_").str[0],axis=1).mean()
df3 = df3.join(df1) 
print(df3)
df3['mean'] = df3.mean(axis=1)
print(df3)
df3.to_excel("public_date.xlsx")

pub_date_all1_1.xlsx
pub_date_all5_1.xlsx
pub_date_all52_2.xlsx
pub_date_all2_2.xlsx
pub_date_all53_2.xlsx
pub_date_all2_1.xlsx
pub_date_all1_2.xlsx
pub_date_all52_1.xlsx
pub_date_all5_2.xlsx
pub_date_all53_1.xlsx
      A094612415T5EHTYKXTQ  A10C50CNO2SJ58  A10G6XGP5G6N6I  A10OFK6JCZFXQH  \
0                      NaN             NaN             NaN             NaN
1                      NaN             NaN             NaN             NaN
2                      NaN             NaN             NaN             NaN
3                      NaN             NaN             NaN             NaN
4                      NaN             NaN             NaN             NaN
...                    ...             ...             ...             ...
1797                   NaN             NaN             NaN             NaN
1798                   NaN             NaN             NaN             NaN
1799                   NaN             NaN             NaN             NaN
1800                   NaN             NaN             NaN             NaN
1801                   NaN             NaN             NaN             NaN

      A10OR73FMTOI6F  A1138Y7XCFT62  A11YQP1EOSZGXU  A1238R4MJ8FJJS  \
0                NaN            NaN             NaN             NaN
1                NaN            NaN             NaN             NaN
2                NaN            NaN             NaN             NaN
3                NaN            NaN             NaN             NaN
4                NaN            NaN             NaN             NaN
...              ...            ...             ...             ...
1797             NaN            NaN             NaN             NaN
1798             NaN            NaN             NaN             NaN
1799             NaN            NaN             NaN             NaN
1800             NaN            NaN             NaN             NaN
1801             NaN            NaN             NaN             NaN

      A12ABRH7TAD6ZJ  A12BIK7GA8NJ9P  ...  AY0758IITCGOZ  AY7RI824FORAE  \
0                NaN             NaN  ...            NaN            NaN
1                NaN             NaN  ...            NaN            1.0
2                NaN             NaN  ...            7.0            NaN
3                NaN             NaN  ...            3.0            NaN
4                NaN             NaN  ...            NaN            NaN
...              ...             ...  ...            ...            ...
1797             NaN             NaN  ...            NaN            NaN
1798             NaN             NaN  ...            NaN            NaN
1799             NaN             NaN  ...            NaN            1.0
1800             NaN             NaN  ...            NaN            1.0
1801             NaN             NaN  ...            NaN            NaN

      AY9TXXA0DTKUS  AYCASFDX49W7Q  AYDCUW23NUJMP  AYQI8UYG2CKP  \
0               NaN            NaN            NaN           NaN
1               NaN            NaN            NaN           NaN
2               NaN            NaN            NaN           NaN
3               NaN            NaN            NaN           NaN
4               NaN            NaN            NaN           NaN
...             ...            ...            ...           ...
1797            NaN            NaN            NaN           NaN
1798            NaN            NaN            NaN           NaN
1799            NaN            NaN            NaN           NaN
1800            NaN            NaN            NaN           NaN
1801            NaN            NaN            NaN           NaN

      AYYH6PRXLFM9T  AZD9Z5B2U40G2  AZU3UVFYHH7NV  \
0               NaN            NaN            NaN
1               NaN            NaN            NaN
2               NaN            NaN            NaN
3               NaN            NaN            NaN
4               NaN            NaN            NaN
...             ...            ...            ...
1797            NaN            NaN            NaN
1798            NaN            NaN            NaN
1799            NaN            NaN            NaN
1800            NaN            NaN            NaN
1801            NaN            6.0            NaN

                                            image
0                                           1.jpg
1                                          10.jpg
2                                        10_1.jpg
3                                          11.jpg
4                                         111.jpg
...                                           ...
1797      pradeep-ranjan-qMrXRcDP5Vw-unsplash.jpg
1798         sayan-ghosh-ZRVmiVKFMDs-unsplash.jpg
1799  temitope-olukayode-bNl3lzD0LpU-unsplash.jpg
1800     theodore-goutas-aeq3jJj0sUw-unsplash.jpg
1801      yogendra-singh-AlpBsZF_uXM-unsplash.jpg

[1802 rows x 482 columns]
      A094612415T5EHTYKXTQ  A10C50CNO2SJ58  A10G6XGP5G6N6I  A10OFK6JCZFXQH  \
0                      NaN             NaN             NaN             NaN
1                      NaN             NaN             NaN             NaN
2                      NaN             NaN             NaN             NaN
3                      NaN             NaN             NaN             NaN
4                      NaN             NaN             NaN             NaN
...                    ...             ...             ...             ...
1797                   NaN             NaN             NaN             NaN
1798                   NaN             NaN             NaN             NaN
1799                   NaN             NaN             NaN             NaN
1800                   NaN             NaN             NaN             NaN
1801                   NaN             NaN             NaN             NaN

      A10OR73FMTOI6F  A1138Y7XCFT62  A11YQP1EOSZGXU  A1238R4MJ8FJJS  \
0                NaN            NaN             NaN             NaN
1                NaN            NaN             NaN             NaN
2                NaN            NaN             NaN             NaN
3                NaN            NaN             NaN             NaN
4                NaN            NaN             NaN             NaN
...              ...            ...             ...             ...
1797             NaN            NaN             NaN             NaN
1798             NaN            NaN             NaN             NaN
1799             NaN            NaN             NaN             NaN
1800             NaN            NaN             NaN             NaN
1801             NaN            NaN             NaN             NaN

      A12ABRH7TAD6ZJ  A12BIK7GA8NJ9P  ...  AY7RI824FORAE  AY9TXXA0DTKUS  \
0                NaN             NaN  ...            NaN            NaN
1                NaN             NaN  ...            1.0            NaN
2                NaN             NaN  ...            NaN            NaN
3                NaN             NaN  ...            NaN            NaN
4                NaN             NaN  ...            NaN            NaN
...              ...             ...  ...            ...            ...
1797             NaN             NaN  ...            NaN            NaN
1798             NaN             NaN  ...            NaN            NaN
1799             NaN             NaN  ...            1.0            NaN
1800             NaN             NaN  ...            1.0            NaN
1801             NaN             NaN  ...            NaN            NaN

      AYCASFDX49W7Q  AYDCUW23NUJMP  AYQI8UYG2CKP  AYYH6PRXLFM9T  \
0               NaN            NaN           NaN            NaN
1               NaN            NaN           NaN            NaN
2               NaN            NaN           NaN            NaN
3               NaN            NaN           NaN            NaN
4               NaN            NaN           NaN            NaN
...             ...            ...           ...            ...
1797            NaN            NaN           NaN            NaN
1798            NaN            NaN           NaN            NaN
1799            NaN            NaN           NaN            NaN
1800            NaN            NaN           NaN            NaN
1801            NaN            NaN           NaN            NaN

      AZD9Z5B2U40G2  AZU3UVFYHH7NV  \
0               NaN            NaN
1               NaN            NaN
2               NaN            NaN
3               NaN            NaN
4               NaN            NaN
...             ...            ...
1797            NaN            NaN
1798            NaN            NaN
1799            NaN            NaN
1800            NaN            NaN
1801            6.0            NaN

                                            image      mean
0                                           1.jpg  6.380000
1                                          10.jpg  5.208333
2                                        10_1.jpg  6.576923
3                                          11.jpg  5.420000
4                                         111.jpg  4.615385
...                                           ...       ...
1797      pradeep-ranjan-qMrXRcDP5Vw-unsplash.jpg  6.777778
1798         sayan-ghosh-ZRVmiVKFMDs-unsplash.jpg  6.705882
1799  temitope-olukayode-bNl3lzD0LpU-unsplash.jpg  3.944444
1800     theodore-goutas-aeq3jJj0sUw-unsplash.jpg  3.062500
1801      yogendra-singh-AlpBsZF_uXM-unsplash.jpg  3.277778

[1802 rows x 483 columns]

In [239]:
#delete a rater and his scores if the number of scores is less than 50
#join scores

df= pd.read_excel('public_generic.xlsx')
min_number= len(df)-50
df4 = df.loc[:, (df.isnull().sum(axis=0) <= min_number)]
df4
df4[df4 > 0].count()

A12WUOCJVJ4C2N    102
A131RGHQUSAJ4A     51
A139BGFGT1F9N1    336
A152OI3N7VA7A1    190
A1580MT585M44G     85
                 ...
AUKAQ17894HDP     480
AW8C7BLRB8CZG     264
AY0758IITCGOZ     171
AYBFVMPV70TDP      61
Unnamed: 0        758
Length: 69, dtype: int64